spring:
  mail:
    host: smtp.gmail.com
    port: 465
    ssl: no
    tls: yes
    username: muxammedovjayxun@gmail.com
    password: glhg mbuo lybj egno
    properties:
      mail:
        smtp:
          auth:
          starttls: false